### ISSUE TITLE
how to download?

### ISSUE THREAD

**Issue by WangChun420** [cbalint13/tinnymodbus#1]
is there have programer on PC? if have ,how to..

**Comment by cbalint13** [comment]
* If have a programmer you need to manual tap clk,miso,mosi,gnd,vcc pins into attiny85 and upload the boot.hex (bootloader) and main.hex (main program) firmware. 
* Once at least boot.hex is burned you can resoft main.hex (main program) right via modbus remotely using remote-flash.sh without needing any programmer. You can upload even your modded version of main.hex anytime and as many time you want.
