### ISSUE TITLE
code size too big

### ISSUE THREAD

**Issue by jgeraerts** [cbalint13/tinnymodbus#10]
I've tried compiling master on my machine with avr-gcc 9.3.0 and the main is overlapping with the bootloader. When I remove the bmp280 code from main.c things fit again, but i was wondering if something else could be done to make it fit again with unmodified code.

```
MAIN:
AVR Memory Usage
----------------
Device: attiny85

Program:    8166 bytes (99.7% Full)
(.text + .data + .bootloader)

Data:         85 bytes (16.6% Full)
(.data + .bss + .noinit)

EEPROM:        1 bytes (0.2% Full)
(.eeprom)


MAIN: 0x0000 - 0x1fe6

BOOT:
AVR Memory Usage
----------------
Device: attiny85

Program:     918 bytes (11.2% Full)
(.text + .data + .bootloader)

Data:        104 bytes (20.3% Full)
(.data + .bss + .noinit)

EEPROM:        1 bytes (0.2% Full)
(.eeprom)
```

**Comment by cbalint13** [comment]
> I've tried compiling master on my machine with avr-gcc 9.3.0 and the main is overlapping with the bootloader. When I remove the bmp280 code from main.c things fit again, but i was wondering if something else could be done to make it fit again with unmodified code.

Hi @jgeraerts,

* Please make sure you are using GCC 8.0.0 . GCC 9 series (not sure about latest GCC 10.2.1) have LTO issues on ```avr``` target (underoptimize on certain cases).

**Comment by jgeraerts** [comment]
Ah that indeed works better. I interpreted the warning of using gcc > 8.0.1 as 9 inclusive. Thank you
