### ISSUE TITLE
general question: UsiUART / SoftUART

### ISSUE THREAD

**Issue by swissiety** [cbalint13/tinnymodbus#18]
Hello,
thank you for providing this nice project for us to adapt and learn.
While exploring the code I recognized, that the bootloader uses softuart while the main program uses usiart for communication - as im quite new to electronics I'd like to ask you to elaborate why it is that way. Thank you in advance.

**Comment by cbalint13** [comment]
Hello Markus,

Thank you for your interest in this little project !

> I recognized, that the bootloader uses softuart while the main program uses usiart for communication - as im quite new to electronics I'd like to ask you to elaborate why it is that way. Thank you in advance.

There was some reasons behind, the hardest was the first one:

  1. The ```usiart``` requires interrupts & fixed interrupt vectors with routines while ```softuart``` is free of such.
     *  ```usiart``` use interrupts (3 of them) and must be shared somehow between ```main``` & ```boot``` (difficult & messy)
     * ```softuart``` , and anything in ```boot``` code does not use any kind of interrupts thus is completley independent.
     * independent ```boot``` means one can swap on the fly back-forth from boot<->main without issues, it is flexible.

  2. The ```usiart``` had a limitation when used on lower speeds like 9600, a safe limit for firmware upgrading.
     * ```usiart``` is not even a complete ```uart``` it is more like a ```serdes``` needing 3 interrupts to handle e.g. 8N1 frames.
     * ironically the code of ```usiart``` is even bigger (due to many handlers)  making it a bad candidate against softuart.
---

Now one can port it to more beefy attiny families having stable crystals and real ```usart`` but hey, this was the real challenge :)
Some deployments have ~5 years of continuous readings, exceeding my expectations, they did very well in bad weather too.

Cheers,
~Cristian.
